### ISSUE TITLE
获取测试实例

### ISSUE THREAD

**Issue by majixin-li** [jinboszu/crp-glah#1]
金老师您好，论文中的测试实例从哪里可以获取到呢？参考论文里的测试实例链接已经失效，不知道您是否可以提供测试实例。
谢谢

**Comment by jinboszu** [comment]
数据都是从各论文的原始网站上下载来的。如果原链接失效的话，你可以在[Shunji Tanaka教授的个人网站](https://sites.google.com/site/shunjitanaka/home)上下载到。

**Comment by majixin-li** [comment]
谢谢金老师提供的链接
